### ISSUE TITLE
verifying zookeeper issue

### ISSUE THREAD

**Issue by shenberg** [open-io/oio-docs#111]
I looked at http://docs.openio.io/admin-guide/operations_sizing.html and the following paragraph struck me as familiar:

> The problem we encounter is that the transaction includes the client’s connection, so that if the transaction fails, the connection of the client will be reset by the cluster’s node. But the FSM (internal to the client) won’t enter in the DISCONNECTED state and the application won’t be able to react on that situation. And an insufficient buffer size is a well-known cause for a transaction to fail. The symptom will be a client app. continuously reconnecting to the Zookeeper cluster, with the service consuming 100% CPU (in the ZK background thread).

How do I verify I'm running against this issue (I see spinning ZK SendThread)?

**Comment by jfsmig** [comment]
Hi @shenberg,
In our use case, the symptom was an error message in the ZK's log. I don't remember the precise shape of the messages, but it was something like `IOException: Len error X` where X was an integer with a value higher than the `jute.maxbuffer` property. Despite this error, using the C client SDK, we've never been notice of a disconnection event.

It happened when we had too many ephemeral nodes (and monitors?) registered in a single ZK client connection. To fix the problem:
* we first changed the value of the property to a value large enough to hold the number of active nodes.
* In a second use case with a huge number f active nodes, we even spread these nodes among a set of connections to the same ZK ensemble (with the help of a hash on the key) thus reducing the number of nodes per transaction, and multiplying the number of background threads.
* Eventually we adapted our tool to shard the nodes over several ZK ensembles, with the same mechanism. This allows you to manage millions of ephemeral nodes.

Hope it helps!
