### ISSUE TITLE
CentOS7 installation don't work. Puppet manifest error.

### ISSUE THREAD

**Issue by ymasson** [open-io/oio-docs#70]
The Puppet manifest, located on doc/install-guide/source/installation.rst, don't work.
`
$ sudo puppet apply --no-stringify_facts /root/openio.pp
Error: Invalid parameter redis_host on Openiosds::Redis[redis-0] at /root/openio.pp:61 on node openio1.local
Wrapped exception:
Invalid parameter redis_host
Error: Invalid parameter redis_host on Openiosds::Redis[redis-0] at /root/openio.pp:61 on node openio1.local
`

**Comment by racciari** [comment]
Hi @ymasson,

thanks for reporting this mistake, this parameter was for redissentinel, I fix this!

**Comment by racciari** [comment]
Fixed in #71
